USE [VK]
GO

/****** Object:  Table [dbo].[friends]    Script Date: 20.11.2015 14:49:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[friends](
	[id] [int] NOT NULL,
	[last_name] [nvarchar](max) NULL,
	[first_name] [nvarchar](max) NULL,
	[sex] [nvarchar](max) NULL,
	[bdate] [nvarchar](max) NULL,
	[photo_50] [nvarchar](max) NULL,
	[photo_100] [nvarchar](max) NULL,
	[photo_200_orig] [nvarchar](max) NULL,
	[photo_200] [nvarchar](max) NULL,
	[photo_400_orig] [nvarchar](max) NULL,
	[photo_max] [nvarchar](max) NULL,
	[photo_max_orig] [nvarchar](max) NULL,
	[photo_id] [nvarchar](max) NULL,
	[online] [nvarchar](max) NULL,
	[online_mobile] [nvarchar](max) NULL,
	[domain] [nvarchar](max) NULL,
	[has_mobile] [nvarchar](max) NULL,
	[contacts] [nvarchar](max) NULL,
	[connections] [nvarchar](max) NULL,
	[site] [nvarchar](max) NULL,
	[education] [nvarchar](max) NULL,
	[universities] [nvarchar](max) NULL,
	[schools] [nvarchar](max) NULL,
	[can_post] [nvarchar](max) NULL,
	[can_see_all_posts] [nvarchar](max) NULL,
	[can_see_audio] [nvarchar](max) NULL,
	[can_write_private_message] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[last_seen] [nvarchar](max) NULL,
	[common_count] [nvarchar](max) NULL,
	[relation] [nvarchar](max) NULL,
	[counters] [nvarchar](max) NULL,
	[screen_name] [nvarchar](max) NULL,
	[maiden_name] [nvarchar](max) NULL,
	[timezone] [nvarchar](max) NULL,
	[activities] [nvarchar](max) NULL,
	[interests] [nvarchar](max) NULL,
	[music] [nvarchar](max) NULL,
	[movies] [nvarchar](max) NULL,
	[tv] [nvarchar](max) NULL,
	[books] [nvarchar](max) NULL,
	[games] [nvarchar](max) NULL,
	[about] [nvarchar](max) NULL,
	[quotes] [nvarchar](max) NULL,
	[personal] [nvarchar](max) NULL,
	[friend_status] [nvarchar](max) NULL,
	[military] [nvarchar](max) NULL,
	[career] [nvarchar](max) NULL,
	[counters_online_friends] [nvarchar](max) NULL,
	[city_id] [nvarchar](max) NULL,
	[country_id] [nvarchar](max) NULL,
	[country_title] [nvarchar](max) NULL,
	[last_seen_time] [nvarchar](max) NULL,
	[occupation_name] [nvarchar](max) NULL,
	[counters_groups] [nvarchar](max) NULL,
	[counters_subscriptions] [nvarchar](max) NULL,
	[counters_videos] [nvarchar](max) NULL,
	[occupation_type] [nvarchar](max) NULL,
	[personal_people_main] [nvarchar](max) NULL,
	[personal_life_main] [nvarchar](max) NULL,
	[personal_political] [nvarchar](max) NULL,
	[personal_smoking] [nvarchar](max) NULL,
	[personal_religion] [nvarchar](max) NULL,
	[last_seen_platform] [nvarchar](max) NULL,
	[city_title] [nvarchar](max) NULL,
	[relatives_id] [nvarchar](max) NULL,
	[relatives_type] [nvarchar](max) NULL,
	[graduation] [nvarchar](max) NULL,
	[home_phone] [nvarchar](max) NULL,
	[faculty] [nvarchar](max) NULL,
	[mobile_phone] [nvarchar](max) NULL,
	[occupation_id] [nvarchar](max) NULL,
	[skype] [nvarchar](max) NULL,
	[personal_alcohol] [nvarchar](max) NULL,
	[personal_inspired_by] [nvarchar](max) NULL,
	[university_name] [nvarchar](max) NULL,
	[faculty_name] [nvarchar](max) NULL,
	[university] [nvarchar](max) NULL,
	[counters_photos] [nvarchar](max) NULL,
	[counters_pages] [nvarchar](max) NULL,
	[counters_followers] [nvarchar](max) NULL,
	[counters_notes] [nvarchar](max) NULL,
	[counters_audios] [nvarchar](max) NULL,
	[counters_user_videos] [nvarchar](max) NULL,
	[counters_friends] [nvarchar](max) NULL,
	[counters_albums] [nvarchar](max) NULL,
	[counters_user_photos] [nvarchar](max) NULL,
	[counters_mutual_friends] [nvarchar](max) NULL,
	[counters_gifts] [nvarchar](max) NULL,
	[online_app] [nvarchar](max) NULL,
	[deactivated] [nvarchar](max) NULL,
	[instagram] [nvarchar](max) NULL,
	[twitter] [nvarchar](max) NULL,
	[relation_partner_id] [nvarchar](max) NULL,
	[relation_partner_last_name] [nvarchar](max) NULL,
	[relation_partner_first_name] [nvarchar](max) NULL,
	[facebook] [nvarchar](max) NULL,
	[facebook_name] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


